/**
 * models/animalmodel.js
 * Base de conocimientos AnimaliaDex — versión expandida ~120 animales
 */

const categoriesData = {

  mamiferos: {
    id: 'mamiferos', name: 'Mamíferos', icon: '🦁', headerIcon: '🐘',
    theme: 'bg-[#986435]', pattern: 'bg-zinc-900',
    descripcion: 'Los mamíferos son vertebrados de sangre caliente que se caracterizan por amamantar a sus crías, tener pelo o pelaje y respirar mediante pulmones.',
    imagen: 'https://i.pinimg.com/736x/32/40/95/3240952750609002e41171b717f3d238.jpg',
    subtypes: [
      {
        name: 'Placentarios', icon: '🦁', color: 'bg-[#717b88]',
        imagen: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=600&q=80',
        descripcion: 'Son el grupo más diverso de mamíferos. Sus crías se desarrollan en el útero materno a través de una placenta que les proporciona nutrición. Incluyen desde ratones hasta ballenas.',
        animales: [
          { nombre: 'León africano', nombreCientifico: 'Panthera leo', altura: '1.2 m', peso: '150–250 kg', habitat: 'Sabanas del África subsahariana', alimentacion: 'Carnívoro — cebras, búfalos, ñus', edadMaxima: '16 años en libertad', comportamiento: 'Vive en manadas. Las hembras son las principales cazadoras.', curiosidades: ['Su rugido se escucha a 8 km.','Duerme hasta 20 horas al día.','Único felino con dimorfismo sexual visible.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Carnivora', familia:'Felidae', imagen:'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=800&q=80' },
          { nombre: 'Elefante africano', nombreCientifico: 'Loxodonta africana', altura: '3.3 m', peso: '4,000–7,000 kg', habitat: 'Sabanas y bosques de África', alimentacion: 'Herbívoro — hierba, hojas, corteza', edadMaxima: '60–70 años', comportamiento: 'Matriarcal. Alta inteligencia emocional.', curiosidades: ['Animal terrestre más grande del mundo.','Puede reconocerse en un espejo.','Usa la trompa para comunicarse.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Proboscidea', familia:'Elephantidae', imagen:'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?w=800&q=80' },
          { nombre: 'Delfín mular', nombreCientifico: 'Tursiops truncatus', altura: '2.5–3.8 m', peso: '150–650 kg', habitat: 'Océanos templados y tropicales', alimentacion: 'Carnívoro — peces, calamares', edadMaxima: '40–50 años', comportamiento: 'Altamente social. Usa ecolocalización para cazar.', curiosidades: ['Duerme con un hemisferio a la vez.','Puede aprender lenguaje de signos.','Cerebro más grande que el humano proporcionalmente.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Artiodactyla', familia:'Delphinidae', imagen:'https://images.unsplash.com/photo-1607153333879-c174d265f1d2?w=800&q=80' },
          { nombre: 'Tigre de Bengala', nombreCientifico: 'Panthera tigris tigris', altura: '1.0 m', peso: '140–300 kg', habitat: 'Bosques de la India y Bangladesh', alimentacion: 'Carnívoro — ciervos, jabalíes, gaur', edadMaxima: '26 años en cautiverio', comportamiento: 'Solitario y territorial. Excelente nadador.', curiosidades: ['El felino más grande del mundo.','Sus rayas son únicas como huellas dactilares.','Puede saltar hasta 9 metros.'], conservacion: 'En peligro (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Carnivora', familia:'Felidae', imagen:'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=800&q=80' },
          { nombre: 'Gorila de montaña', nombreCientifico: 'Gorilla beringei beringei', altura: '1.7 m', peso: '140–220 kg', habitat: 'Montañas volcánicas de África Central', alimentacion: 'Herbívoro — hojas, tallos, frutos', edadMaxima: '40–50 años', comportamiento: 'Vive en grupos familiares liderados por un macho "espalda plateada".', curiosidades: ['Comparte el 98.3% del ADN humano.','Se comunica con más de 25 vocalizaciones.','Construye un nuevo nido cada noche.'], conservacion: 'En peligro crítico (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Primates', familia:'Hominidae', imagen:'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80' },
          { nombre: 'Ballena azul', nombreCientifico: 'Balaenoptera musculus', altura: '24–33 m', peso: 'hasta 200,000 kg', habitat: 'Todos los océanos del mundo', alimentacion: 'Filtradora — kril', edadMaxima: '80–90 años', comportamiento: 'Migratoria. Cría solitaria o en pares.', curiosidades: ['El animal más grande que ha existido.','Su corazón pesa 600 kg.','Su llamado es el más alto del reino animal: 188 dB.'], conservacion: 'En peligro (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Artiodactyla', familia:'Balaenopteridae', imagen:'https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=800&q=80' },
          { nombre: 'Lobo gris', nombreCientifico: 'Canis lupus', altura: '80–85 cm', peso: '30–80 kg', habitat: 'Bosques, tundra y montañas del hemisferio norte', alimentacion: 'Carnívoro — alces, ciervos, conejos', edadMaxima: '16 años', comportamiento: 'Vive en manadas con jerarquía estricta.', curiosidades: ['Ancestro de todos los perros domésticos.','Puede recorrer 200 km en un día.','Su aullido se sincroniza con el grupo.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Carnivora', familia:'Canidae', imagen:'https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80' },
          { nombre: 'Murciélago vampiro común', nombreCientifico: 'Desmodus rotundus', altura: '7–9 cm', peso: '25–40 g', habitat: 'América Central y del Sur tropical', alimentacion: 'Hematófago — sangre de ganado y aves', edadMaxima: '12 años', comportamiento: 'Nocturno. Comparte sangre con compañeros de colonia.', curiosidades: ['Única especie de murciélago que no puede caminar en reversa.','Detecta venas con receptores de calor en la nariz.','Orina mientras come para aligerar su peso.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Chiroptera', familia:'Phyllostomidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      },
      {
        name: 'Marsupiales', icon: '🦘', color: 'bg-[#f4bc83]',
        imagen: 'https://i1-e.pinimg.com/736x/9c/87/d5/9c87d5ac4ce043ab29b14caf509d7c00.jpg',
        descripcion: 'Los marsupiales dan a luz crías en etapa muy temprana de desarrollo. Las crías completan su desarrollo dentro de una bolsa o marsupio en el vientre de la madre.',
        animales: [
          { nombre: 'Canguro rojo', nombreCientifico: 'Osphranter rufus', altura: '1.5 m', peso: '55–90 kg', habitat: 'Zonas áridas de Australia', alimentacion: 'Herbívoro — pastos y arbustos', edadMaxima: '22 años', comportamiento: 'Los machos compiten con "boxeo".', curiosidades: ['El marsupial más grande del mundo.','Puede detener el desarrollo de un embrión.','La cría nace del tamaño de un cacahuate.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Diprotodontia', familia:'Macropodidae', imagen:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80' },
          { nombre: 'Koala', nombreCientifico: 'Phascolarctos cinereus', altura: '60–85 cm', peso: '4–15 kg', habitat: 'Bosques de eucaliptos de Australia', alimentacion: 'Herbívoro — hojas de eucalipto', edadMaxima: '18 años', comportamiento: 'Solitario. Duerme hasta 22 horas.', curiosidades: ['Las hojas de eucalipto son tóxicas para casi todos.','Sus huellas son casi idénticas a las humanas.','No son osos.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Diprotodontia', familia:'Phascolarctidae', imagen:'https://images.unsplash.com/photo-1459262838948-3e2de6c1ec80?w=800&q=80' },
          { nombre: 'Diablo de Tasmania', nombreCientifico: 'Sarcophilus harrisii', altura: '25–30 cm', peso: '6–12 kg', habitat: 'Bosques y pastizales de Tasmania', alimentacion: 'Carnívoro — carroña, mamíferos pequeños', edadMaxima: '6 años', comportamiento: 'Solitario y nocturno. Conocido por sus chillidos.', curiosidades: ['La mordida más fuerte en proporción a su tamaño entre mamíferos.','Sufre una enfermedad tumoral facial transmisible única.','Come huesos, pelo y todo del animal.'], conservacion: 'En peligro (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Dasyuromorphia', familia:'Dasyuridae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' },
          { nombre: 'Wombat común', nombreCientifico: 'Vombatus ursinus', altura: '70–110 cm', peso: '20–35 kg', habitat: 'Bosques y praderas del sureste de Australia', alimentacion: 'Herbívoro — pasto, raíces', edadMaxima: '26 años', comportamiento: 'Excavador. Cava madrigueras de hasta 30 m.', curiosidades: ['El único animal que produce heces cúbicas.','Tiene el marsupio orientado hacia atrás para no llenar de tierra.','Sus huesos de la espalda son extremadamente resistentes.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Diprotodontia', familia:'Vombatidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' }
        ]
      },
      {
        name: 'Monotremas', icon: '🦆', color: 'bg-[#a37952]',
        imagen: 'https://i1-e.pinimg.com/1200x/26/15/43/261543baf8ec732080eaf4e503fbede4.jpg',
        descripcion: 'Los monotremas son los únicos mamíferos que ponen huevos. Son considerados los mamíferos más primitivos. Solo existen 5 especies vivas en el mundo.',
        animales: [
          { nombre: 'Ornitorrinco', nombreCientifico: 'Ornithorhynchus anatinus', altura: '38–60 cm', peso: '0.7–2.4 kg', habitat: 'Ríos y lagos del este de Australia', alimentacion: 'Carnívoro — larvas, gusanos, crustáceos', edadMaxima: '17 años', comportamiento: 'Solitario y semiacuático. Detecta campos eléctricos.', curiosidades: ['Pone huevos siendo mamífero.','Los machos tienen espolón venenoso.','No tiene estómago.'], conservacion: 'Casi amenazado (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Monotremata', familia:'Ornithorhynchidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' },
          { nombre: 'Equidna de hocico corto', nombreCientifico: 'Tachyglossus aculeatus', altura: '30–45 cm', peso: '2–7 kg', habitat: 'Australia y Nueva Guinea, bosques y matorrales', alimentacion: 'Insectívoro — hormigas y termitas', edadMaxima: '50 años', comportamiento: 'Solitario. Se enrolla en bola cuando hay peligro.', curiosidades: ['Pone huevos y los lleva en su bolsa.','Su pene tiene 4 cabezas.','Entra en torpor cuando hace frío.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Mammalia', orden:'Monotremata', familia:'Tachyglossidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' }
        ]
      }
    ]
  },

  aves: {
    id: 'aves', name: 'Aves', icon: '🦜', headerIcon: '🦅',
    theme: 'bg-sky-600', pattern: 'bg-slate-900',
    descripcion: 'Las aves son vertebrados de sangre caliente cuyo cuerpo está cubierto de plumas. Se reproducen poniendo huevos y la mayoría posee la capacidad de volar.',
    imagen: 'https://i1-e.pinimg.com/1200x/a0/8a/a9/a08aa9e6630c2048c1f6342dda158a4a.jpg',
    subtypes: [
      {
        name: 'Voladoras', icon: '🕊️', color: 'bg-sky-300',
        imagen: 'https://i1-e.pinimg.com/1200x/e9/64/68/e96468835cbd089c74dd46c36f6d8d17.jpg',
        descripcion: 'La gran mayoría de las aves pertenecen a este grupo. Poseen alas funcionales, huesos huecos y musculatura pectoral potente adaptada para el vuelo.',
        animales: [
          { nombre: 'Águila calva', nombreCientifico: 'Haliaeetus leucocephalus', altura: '71–96 cm', peso: '3–6.3 kg', habitat: 'Costas y ríos de América del Norte', alimentacion: 'Carnívora — principalmente peces', edadMaxima: '28 años', comportamiento: 'Territorial. Construye los nidos más grandes de Norteamérica.', curiosidades: ['Símbolo nacional de EE.UU.','Ve 4–8 veces más nítido que un humano.','Su llamado real es débil.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Aves', orden:'Accipitriformes', familia:'Accipitridae', imagen:'https://images.unsplash.com/photo-1611689342806-0863700a1c20?w=800&q=80' },
          { nombre: 'Colibrí gorjinegro', nombreCientifico: 'Archilochus alexandri', altura: '8–9 cm', peso: '2.8–3.5 g', habitat: 'Jardines y bosques del oeste de Norteamérica', alimentacion: 'Nectarívoro — néctar e insectos', edadMaxima: '12 años', comportamiento: 'Solitario y territorial. Único pájaro que vuela hacia atrás.', curiosidades: ['Bate las alas 50–80 veces por segundo.','Corazón late 1,200 veces por minuto.','Entra en torpor nocturno.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Aves', orden:'Apodiformes', familia:'Trochilidae', imagen:'https://images.unsplash.com/photo-1444464666168-49d633b86797?w=800&q=80' },
          { nombre: 'Cóndor andino', nombreCientifico: 'Vultur gryphus', altura: '1–1.3 m', peso: '8–15 kg', habitat: 'Andes de América del Sur', alimentacion: 'Carroñero — cadáveres de grandes mamíferos', edadMaxima: '70 años', comportamiento: 'Vuela sin aletear usando corrientes térmicas.', curiosidades: ['La envergadura más grande de cualquier ave terrestre: 3.3 m.','Puede planear 5 horas sin mover las alas.','Símbolo nacional de 6 países sudamericanos.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Chordata', clase:'Aves', orden:'Cathartiformes', familia:'Cathartidae', imagen:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80' },
          { nombre: 'Loro gris africano', nombreCientifico: 'Psittacus erithacus', altura: '33 cm', peso: '400–650 g', habitat: 'Bosques del África ecuatorial', alimentacion: 'Omnívoro — semillas, frutos, nueces', edadMaxima: '60 años en cautiverio', comportamiento: 'Altamente social. Forma parejas de por vida.', curiosidades: ['El pájaro más inteligente documentado.','Comprende conceptos como "cero" y "más grande que".','Puede imitar voces humanas con precisión.'], conservacion: 'En peligro (UICN)', reino:'Animalia', filo:'Chordata', clase:'Aves', orden:'Psittaciformes', familia:'Psittacidae', imagen:'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=800&q=80' },
          { nombre: 'Albatros viajero', nombreCientifico: 'Diomedea exulans', altura: '1.1–1.35 m', peso: '6–12 kg', habitat: 'Océano Austral y sur del Pacífico', alimentacion: 'Carnívoro — calamares y peces', edadMaxima: '60 años', comportamiento: 'Pasa años enteros sin tocar tierra.', curiosidades: ['La mayor envergadura de cualquier ave viva: hasta 3.7 m.','Puede dormir mientras vuela.','Recorre 120,000 km al año.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Chordata', clase:'Aves', orden:'Procellariiformes', familia:'Diomedeidae', imagen:'https://images.unsplash.com/photo-1504173010664-32509107de98?w=800&q=80' }
        ]
      },
      {
        name: 'No Voladoras', icon: '🐧', color: 'bg-slate-400',
        imagen: 'https://i1-e.pinimg.com/1200x/dc/22/e7/dc22e72f0d0c2d63136b4f94a74b7611.jpg',
        descripcion: 'Aves que perdieron la capacidad de volar a lo largo de la evolución. Sus alas se adaptaron para nadar, correr o simplemente se redujeron. Son generalmente más grandes.',
        animales: [
          { nombre: 'Pingüino emperador', nombreCientifico: 'Aptenodytes forsteri', altura: '110–130 cm', peso: '22–45 kg', habitat: 'Antártida', alimentacion: 'Carnívoro — peces, calamares, kril', edadMaxima: '20 años', comportamiento: 'Los machos incuban el huevo en invierno antártico.', curiosidades: ['Bucea hasta 565 m.','Soporta -60°C.','El pingüino más grande del mundo.'], conservacion: 'Casi amenazado (UICN)', reino:'Animalia', filo:'Chordata', clase:'Aves', orden:'Sphenisciformes', familia:'Spheniscidae', imagen:'https://images.unsplash.com/photo-1598439210625-5067c578f3f6?w=800&q=80' },
          { nombre: 'Avestruz', nombreCientifico: 'Struthio camelus', altura: '2.1–2.8 m', peso: '63–145 kg', habitat: 'Sabanas y desiertos de África', alimentacion: 'Omnívoro — plantas, insectos, lagartijas', edadMaxima: '40–45 años', comportamiento: 'Corre hasta 70 km/h.', curiosidades: ['El ave más grande del mundo.','Sus ojos miden 5 cm — los más grandes de vertebrado terrestre.','Bípedo más rápido del planeta.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Aves', orden:'Struthioniformes', familia:'Struthionidae', imagen:'https://images.unsplash.com/photo-1508190963171-9f372b937bc3?w=800&q=80' },
          { nombre: 'Casuario del sur', nombreCientifico: 'Casuarius casuarius', altura: '1.5–2 m', peso: '50–85 kg', habitat: 'Selvas tropicales de Nueva Guinea y Australia', alimentacion: 'Omnívoro — frutas caídas, hongos, pequeños animales', edadMaxima: '40–50 años', comportamiento: 'Solitario y territorial. El macho cuida los huevos.', curiosidades: ['El ave más peligrosa del mundo.','Su garra interior puede medir 12 cm.','La cresura ósea actúa como casco en la selva.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Chordata', clase:'Aves', orden:'Casuariiformes', familia:'Casuariidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' },
          { nombre: 'Kiwi común', nombreCientifico: 'Apteryx australis', altura: '45–55 cm', peso: '1.4–3 kg', habitat: 'Bosques de Nueva Zelanda', alimentacion: 'Omnívoro — lombrices, insectos, frutos', edadMaxima: '25–50 años', comportamiento: 'Nocturno. Pareja de por vida.', curiosidades: ['Único pájaro con fosas nasales en la punta del pico.','Pone el huevo más grande en proporción a su cuerpo.','Sus plumas parecen pelo.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Chordata', clase:'Aves', orden:'Apterygiformes', familia:'Apterygidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' }
        ]
      },
      {
        name: 'Acuáticas', icon: '🦆', color: 'bg-teal-400',
        imagen: 'https://i1-e.pinimg.com/736x/87/3e/cf/873ecfbf84061cf5b1f048fea7c99c04.jpg',
        descripcion: 'Aves adaptadas a vivir en o cerca del agua. Tienen patas palmeadas, plumaje impermeable y picos especializados para filtrar o atrapar presas en el agua.',
        animales: [
          { nombre: 'Flamenco común', nombreCientifico: 'Phoenicopterus roseus', altura: '1.2–1.45 m', peso: '2–4 kg', habitat: 'Lagos salinos de África, Europa del sur y Asia', alimentacion: 'Filtrador — algas y crustáceos', edadMaxima: '40 años', comportamiento: 'Gregario. Duerme parado en un solo pie.', curiosidades: ['Su color viene de su dieta.','Los polluelos nacen blancos.','Filtra el agua con el pico invertido.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Aves', orden:'Phoenicopteriformes', familia:'Phoenicopteridae', imagen:'https://images.unsplash.com/photo-1497206365907-f5e630693df0?w=800&q=80' },
          { nombre: 'Pelícano pardo', nombreCientifico: 'Pelecanus occidentalis', altura: '1–1.5 m', peso: '2.8–5.5 kg', habitat: 'Costas de América', alimentacion: 'Carnívoro — peces', edadMaxima: '30 años', comportamiento: 'Caza zambulléndose en picada desde el aire.', curiosidades: ['Su bolsa gular puede contener 11 litros de agua.','Navega en formación para ahorrar energía.','Símbolo de Luisiana (EE.UU.).'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Aves', orden:'Pelecaniformes', familia:'Pelecanidae', imagen:'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=80' },
          { nombre: 'Cisne de Bewick', nombreCientifico: 'Cygnus bewickii', altura: '1.15–1.27 m', peso: '4.2–7.8 kg', habitat: 'Tundra ártica y humedales templados de Eurasia', alimentacion: 'Herbívoro — plantas acuáticas', edadMaxima: '24 años', comportamiento: 'Migra más de 4,000 km. Parejas de por vida.', curiosidades: ['Cada individuo tiene un patrón de manchas amarillas único.','Las parejas se reúnen tras la migración con vocalizaciones.','Los polluelos migran con sus padres el primer año.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Aves', orden:'Anseriformes', familia:'Anatidae', imagen:'https://images.unsplash.com/photo-1566847438217-76e82d3f9ca8?w=800&q=80' }
        ]
      }
    ]
  },

  reptiles: {
    id: 'reptiles', name: 'Reptiles', icon: '🐍', headerIcon: '🐊',
    theme: 'bg-emerald-700', pattern: 'bg-stone-900',
    descripcion: 'Los reptiles son vertebrados de sangre fría con cuerpo cubierto de escamas. Respiran por pulmones y la mayoría se reproduce poniendo huevos.',
    imagen: 'https://i.pinimg.com/736x/45/bf/f2/45bff221e32b3f762e297c82440ffb7c.jpg',
    subtypes: [
      {
        name: 'Escamosos', icon: '🦎', color: 'bg-emerald-400',
        imagen: 'https://i1-e.pinimg.com/1200x/b1/71/e4/b171e4b05209abb5aecadf6768bba9a7.jpg',
        descripcion: 'El orden más diverso de reptiles. Incluye lagartos y serpientes. Se caracterizan por sus escamas queratinizadas y la muda periódica de piel.',
        animales: [
          { nombre: 'Dragón de Komodo', nombreCientifico: 'Varanus komodoensis', altura: '2.5–3 m', peso: '70–90 kg', habitat: 'Islas de Indonesia', alimentacion: 'Carnívoro — ciervos, jabalíes', edadMaxima: '30 años', comportamiento: 'Solitario y emboscador.', curiosidades: ['El lagarto más grande del mundo.','Su saliva contiene veneno anticoagulante.','Las hembras pueden reproducirse sin macho.'], conservacion: 'En peligro (UICN)', reino:'Animalia', filo:'Chordata', clase:'Reptilia', orden:'Squamata', familia:'Varanidae', imagen:'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=800&q=80' },
          { nombre: 'Anaconda verde', nombreCientifico: 'Eunectes murinus', altura: '5–8 m', peso: '30–250 kg', habitat: 'Selvas y pantanos de América del Sur', alimentacion: 'Carnívora — capibaras, caimanes', edadMaxima: '30 años', comportamiento: 'Semiacuática. Constrictora.', curiosidades: ['La serpiente más pesada del mundo.','Puede pasar un año sin comer.','Detecta calor con fosas termorreceptoras.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Reptilia', orden:'Squamata', familia:'Boidae', imagen:'https://images.unsplash.com/photo-1497752531616-c3afd9760a11?w=800&q=80' },
          { nombre: 'Camaleón de Jackson', nombreCientifico: 'Trioceros jacksonii', altura: '25–38 cm', peso: '90–150 g', habitat: 'Bosques montanos de Kenia y Tanzania', alimentacion: 'Insectívoro — grillos, langostas', edadMaxima: '5–10 años', comportamiento: 'Solitario. Los machos tienen tres cuernos para combatir.', curiosidades: ['Cambia de color para comunicar estados de ánimo, no por camuflaje.','Sus ojos giran de forma independiente 360°.','Su lengua sale a 60 km/h.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Reptilia', orden:'Squamata', familia:'Chamaeleonidae', imagen:'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=80' },
          { nombre: 'Cobra real', nombreCientifico: 'Ophiophagus hannah', altura: '3–5.5 m', peso: '6–12 kg', habitat: 'Selvas del sur y sureste de Asia', alimentacion: 'Carnívora — otras serpientes', edadMaxima: '20 años', comportamiento: 'Territorial. La única serpiente que construye nido.', curiosidades: ['La serpiente venenosa más larga del mundo.','Su veneno puede matar a un elefante en horas.','El único reptil que cuida activamente sus huevos.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Chordata', clase:'Reptilia', orden:'Squamata', familia:'Elapidae', imagen:'https://images.unsplash.com/photo-1531386151447-fd76ad50012f?w=800&q=80' },
          { nombre: 'Gecko tokay', nombreCientifico: 'Gekko gecko', altura: '25–35 cm', peso: '100–300 g', habitat: 'Selvas tropicales del sur de Asia', alimentacion: 'Carnívoro — insectos, pequeños vertebrados', edadMaxima: '10 años', comportamiento: 'Nocturno y territorial. Produce llamados fuertes.', curiosidades: ['Sus patas tienen millones de nanofibras que permiten adherirse a casi cualquier superficie.','Puede soltar su cola para escapar y luego regenerarla.','Sus ojos no tienen párpados — los limpian con la lengua.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Reptilia', orden:'Squamata', familia:'Gekkonidae', imagen:'https://images.unsplash.com/photo-1550358864-518f202c02ba?w=800&q=80' }
        ]
      },
      {
        name: 'Testudines', icon: '🐢', color: 'bg-lime-500',
        imagen: 'https://i1-e.pinimg.com/1200x/fb/21/a0/fb21a0f3586a8b3cbfc5248748f16263.jpg',
        descripcion: 'Las tortugas son reptiles con un caparazón óseo que protege su cuerpo. Son uno de los grupos de vertebrados más antiguos, con más de 220 millones de años de historia.',
        animales: [
          { nombre: 'Tortuga gigante de Galápagos', nombreCientifico: 'Chelonoidis niger', altura: '1.5 m', peso: '180–300 kg', habitat: 'Islas Galápagos, Ecuador', alimentacion: 'Herbívora — cactus, pasto', edadMaxima: 'Más de 170 años', comportamiento: 'Solitaria. Puede sobrevivir un año sin agua.', curiosidades: ['El reptil más longevo del mundo.','Inspiró a Darwin.','El último de su subespecie fue "Solitario George".'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Chordata', clase:'Reptilia', orden:'Testudines', familia:'Testudinidae', imagen:'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80' },
          { nombre: 'Tortuga laúd', nombreCientifico: 'Dermochelys coriacea', altura: '1.5–1.8 m', peso: '250–700 kg', habitat: 'Todos los océanos', alimentacion: 'Carnívora — medusas', edadMaxima: '45 años', comportamiento: 'Migradora de larga distancia.', curiosidades: ['El reptil más grande del mundo.','Bucea hasta 1,280 m — más que ninguna otra tortuga.','No tiene caparazón óseo duro sino piel coriácea.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Chordata', clase:'Reptilia', orden:'Testudines', familia:'Dermochelyidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' },
          { nombre: 'Tortuga mordedora', nombreCientifico: 'Chelydra serpentina', altura: '20–36 cm caparazón', peso: '4.5–16 kg', habitat: 'Ríos y lagos de América del Norte y Central', alimentacion: 'Omnívora — peces, aves, plantas acuáticas', edadMaxima: '30–40 años', comportamiento: 'Agresiva fuera del agua. Pasa la mayor parte del tiempo sumergida.', curiosidades: ['No puede retraer la cabeza completamente en el caparazón.','Su mordida puede cortar un palo de madera.','Detiene el metabolismo bajo el hielo en invierno.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Reptilia', orden:'Testudines', familia:'Chelydridae', imagen:'https://images.unsplash.com/photo-1531386151447-fd76ad50012f?w=800&q=80' }
        ]
      },
      {
        name: 'Cocodrilianos', icon: '🐊', color: 'bg-green-800',
        imagen: 'https://i1-e.pinimg.com/1200x/34/75/b6/3475b66cacee9fce89a04522d4fe3869.jpg',
        descripcion: 'Los cocodrilianos son los reptiles más grandes del mundo. Tienen un corazón de cuatro cámaras similar al de los mamíferos y son los parientes vivos más cercanos de las aves.',
        animales: [
          { nombre: 'Cocodrilo del Nilo', nombreCientifico: 'Crocodylus niloticus', altura: '3.5–6 m', peso: '225–750 kg', habitat: 'Ríos y lagos de África subsahariana', alimentacion: 'Carnívoro — peces, cebras, búfalos', edadMaxima: '70–80 años', comportamiento: 'Territorial. Cuida a sus crías sorprendentemente.', curiosidades: ['Mordida más fuerte del reino animal: 5,000 N.','No puede masticar, traga entero.','La temperatura del nido determina el sexo.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Reptilia', orden:'Crocodilia', familia:'Crocodylidae', imagen:'https://images.unsplash.com/photo-1582967788606-a171c1080cb0?w=800&q=80' },
          { nombre: 'Gavial del Ganges', nombreCientifico: 'Gavialis gangeticus', altura: '3.5–6 m', peso: '160–250 kg', habitat: 'Ríos del norte de la India y Nepal', alimentacion: 'Carnívoro — peces principalmente', edadMaxima: '50–60 años', comportamiento: 'Semi-acuático. Los machos hacen sonidos con la protuberancia nasal.', curiosidades: ['Hocico más largo de todos los cocodrilianos — adaptado para pescar.','Uno de los reptiles más amenazados del mundo.','No puede caminar erguido, solo arrastrarse.'], conservacion: 'En peligro crítico (UICN)', reino:'Animalia', filo:'Chordata', clase:'Reptilia', orden:'Crocodilia', familia:'Gavialidae', imagen:'https://images.unsplash.com/photo-1497206365907-f5e630693df0?w=800&q=80' },
          { nombre: 'Caimán negro', nombreCientifico: 'Melanosuchus niger', altura: '3–6 m', peso: '200–400 kg', habitat: 'Cuenca amazónica', alimentacion: 'Carnívoro — peces, anacondas, tapires', edadMaxima: '50–80 años', comportamiento: 'Depredador nocturno. Caza solo.', curiosidades: ['El cocodrilo más grande de América.','Su presión de mordida supera la del cocodrilo del Nilo.','Sus ojos reflejan luz roja en la oscuridad.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Reptilia', orden:'Crocodilia', familia:'Alligatoridae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      }
    ]
  },

  anfibios: {
    id: 'anfibios', name: 'Anfibios', icon: '🐸', headerIcon: '🐸',
    theme: 'bg-teal-600', pattern: 'bg-zinc-800',
    descripcion: 'Los anfibios son vertebrados que viven tanto en el agua como en la tierra. Su piel es húmeda y permeable, y la mayoría tiene una metamorfosis de larva acuática a adulto terrestre.',
    imagen: 'https://i.pinimg.com/736x/9b/f5/c4/9bf5c4d5fdc51568fa9436bb41bb7b6b.jpg',
    subtypes: [
      {
        name: 'Anuros', icon: '🐸', color: 'bg-teal-400',
        imagen: 'https://i1-e.pinimg.com/1200x/1a/45/e9/1a45e96dda687c313c7774fe2f41d651.jpg',
        descripcion: 'Las ranas y sapos. Sin cola en estado adulto. Son los anfibios más diversos y abundantes. Muchas especies tienen piel colorida como señal de peligro.',
        animales: [
          { nombre: 'Rana dardo dorada', nombreCientifico: 'Phyllobates terribilis', altura: '4–5 cm', peso: '3 g', habitat: 'Selvas del Pacífico colombiano', alimentacion: 'Insectívora — hormigas, ácaros', edadMaxima: '10–15 años', comportamiento: 'Diurna y territorial.', curiosidades: ['El animal más venenoso del mundo.','Un ejemplar puede matar a 10 personas.','En cautiverio pierde su toxicidad.'], conservacion: 'En peligro (UICN)', reino:'Animalia', filo:'Chordata', clase:'Amphibia', orden:'Anura', familia:'Dendrobatidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' },
          { nombre: 'Rana de cristal', nombreCientifico: 'Centrolenidae spp.', altura: '2–3 cm', peso: '1–2 g', habitat: 'Selvas tropicales de América Central y del Sur', alimentacion: 'Insectívora — moscas y mosquitos', edadMaxima: '10–14 años', comportamiento: 'Nocturna. Los machos cuidan los huevos en hojas sobre el agua.', curiosidades: ['Su piel es completamente transparente — se ve su corazón latir.','Sus huesos son verdes.','Duermen con los ojos cubiertos por sus órbitas para camuflarse.'], conservacion: 'Varía por especie', reino:'Animalia', filo:'Chordata', clase:'Amphibia', orden:'Anura', familia:'Centrolenidae', imagen:'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=800&q=80' },
          { nombre: 'Rana toro americana', nombreCientifico: 'Lithobates catesbeianus', altura: '9–15 cm', peso: '300–500 g', habitat: 'Estanques y ríos de América del Norte', alimentacion: 'Carnívora — insectos, ratones, peces pequeños, otras ranas', edadMaxima: '16 años', comportamiento: 'Territorial. Los machos emiten un mugido grave.', curiosidades: ['Devora cualquier cosa que quepa en su boca.','Es una especie invasora en varios continentes.','Sus renacuajos pueden tardar 2 años en metamorfosearse.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Amphibia', orden:'Anura', familia:'Ranidae', imagen:'https://images.unsplash.com/photo-1551969014-7d2c4cddf0b6?w=800&q=80' },
          { nombre: 'Sapo de Surinam', nombreCientifico: 'Pipa pipa', altura: '10–17 cm', peso: '60–100 g', habitat: 'Ríos y pantanos de América del Sur tropical', alimentacion: 'Carnívoro — gusanos, crustáceos', edadMaxima: '8 años', comportamiento: 'Completamente acuático. Los renacuajos eclosionan desde la espalda de la madre.', curiosidades: ['Las crías se desarrollan dentro de la piel de la espalda de la madre.','No tiene lengua.','Su cuerpo es completamente plano.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Amphibia', orden:'Anura', familia:'Pipidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      },
      {
        name: 'Urodelos', icon: '🦎', color: 'bg-cyan-600',
        imagen: 'https://i1-e.pinimg.com/1200x/5b/4e/51/5b4e5192c3a3e2dfb56a72e4b797bf0a.jpg',
        descripcion: 'Las salamandras y tritones. Conservan la cola durante toda su vida. Algunos mantienen características larvales incluso en la etapa adulta (neotenia).',
        animales: [
          { nombre: 'Ajolote mexicano', nombreCientifico: 'Ambystoma mexicanum', altura: '23–30 cm', peso: '60–100 g', habitat: 'Lagos de Xochimilco, Ciudad de México', alimentacion: 'Carnívoro — gusanos, insectos, peces pequeños', edadMaxima: '15 años', comportamiento: 'Neoténico — mantiene branquias externas toda la vida.', curiosidades: ['Puede regenerar extremidades y partes del cerebro.','Símbolo cultural azteca.','Menos de 1,000 en vida silvestre.'], conservacion: 'En peligro crítico (UICN)', reino:'Animalia', filo:'Chordata', clase:'Amphibia', orden:'Urodela', familia:'Ambystomatidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' },
          { nombre: 'Salamandra gigante china', nombreCientifico: 'Andrias davidianus', altura: '1.1–1.8 m', peso: '25–50 kg', habitat: 'Ríos y arroyos de montaña de China', alimentacion: 'Carnívora — peces, cangrejos, ranas', edadMaxima: '60 años', comportamiento: 'Nocturna y semiacuática. Detecta vibraciones.', curiosidades: ['El anfibio más grande del mundo.','Se comunica con chillidos similares al llanto de un bebé.','Prácticamente ciega — caza por quimiorrecepción.'], conservacion: 'En peligro crítico (UICN)', reino:'Animalia', filo:'Chordata', clase:'Amphibia', orden:'Urodela', familia:'Cryptobranchidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' },
          { nombre: 'Salamandra de fuego', nombreCientifico: 'Salamandra salamandra', altura: '15–25 cm', peso: '20–40 g', habitat: 'Bosques húmedos y caducifolios de Europa', alimentacion: 'Carnívora — lombrices, insectos, babosas', edadMaxima: '25 años', comportamiento: 'Nocturna y terrestre. Solitaria.', curiosidades: ['Su piel segrega un alcaloide tóxico llamado salamandrina.','Pare crías vivas, no pone huevos.','Las manchas amarillas son únicas por individuo.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Amphibia', orden:'Urodela', familia:'Salamandridae', imagen:'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=800&q=80' }
        ]
      },
      {
        name: 'Ápodos', icon: '🪱', color: 'bg-stone-500',
        imagen: 'https://i1-e.pinimg.com/1200x/2e/af/89/2eaf89eadcbd331150745c8bbcd1d574.jpg',
        descripcion: 'Las cecilias. Anfibios sin extremidades ni cola visible. Viven enterrados en suelos húmedos o en ríos. Son los anfibios menos conocidos por su estilo de vida subterráneo.',
        animales: [
          { nombre: 'Cecilia de Thompson', nombreCientifico: 'Caecilia thompsoni', altura: 'hasta 150 cm', peso: 'aprox. 1 kg', habitat: 'Suelos húmedos de Colombia', alimentacion: 'Carnívora — lombrices y larvas', edadMaxima: '~13 años', comportamiento: 'Subterránea y fosorial.', curiosidades: ['La cecilia más larga conocida.','Tienen tentáculos sensoriales.','Algunas dan leche raspando su propia piel.'], conservacion: 'Datos insuficientes (UICN)', reino:'Animalia', filo:'Chordata', clase:'Amphibia', orden:'Gymnophiona', familia:'Caeciliidae', imagen:'https://images.unsplash.com/photo-1535083783855-ded51a9b5041?w=800&q=80' },
          { nombre: 'Cecilia acuática', nombreCientifico: 'Typhlonectes natans', altura: '40–60 cm', peso: '40–80 g', habitat: 'Ríos de Colombia y Venezuela', alimentacion: 'Carnívora — lombrices, larvas acuáticas', edadMaxima: '~10 años', comportamiento: 'Acuática. Respira subiendo a la superficie.', curiosidades: ['Una de las pocas cecilias completamente acuáticas.','La más popular en acuarios por su rareza.','Se comunica con clicks ultrasónicos.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Amphibia', orden:'Gymnophiona', familia:'Typhlonectidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      }
    ]
  },

  peces: {
    id: 'peces', name: 'Peces', icon: '🦈', headerIcon: '🦈',
    theme: 'bg-blue-700', pattern: 'bg-slate-900',
    descripcion: 'Los peces son vertebrados acuáticos que respiran mediante branquias. Son el grupo más diverso de vertebrados con más de 33,000 especies conocidas.',
    imagen: 'https://i1-e.pinimg.com/1200x/c3/be/6a/c3be6a4caafee9d54fe15e60859f1f6d.jpg',
    subtypes: [
      {
        name: 'Óseos', icon: '🐠', color: 'bg-blue-400',
        imagen: 'https://i1-e.pinimg.com/1200x/ea/22/d5/ea22d5f645fb3bbf2630cc78c033a0a1.jpg',
        descripcion: 'Los peces óseos constituyen más del 95% de todas las especies de peces. Se distinguen por tener un esqueleto calcificado y una vejiga natatoria para controlar la flotación.',
        animales: [
          { nombre: 'Pez payaso', nombreCientifico: 'Amphiprion ocellaris', altura: '8–11 cm', peso: '8–10 g', habitat: 'Arrecifes de coral del Indo-Pacífico', alimentacion: 'Omnívoro — algas y zooplancton', edadMaxima: '6–10 años', comportamiento: 'Vive en simbiosis con anémonas.', curiosidades: ['Todos nacen machos; el dominante se vuelve hembra.','Inmunes al veneno de las anémonas.','Nemo disparó su demanda como mascota.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Actinopterygii', orden:'Perciformes', familia:'Pomacentridae', imagen:'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80' },
          { nombre: 'Pez luna', nombreCientifico: 'Mola mola', altura: '1.8–3 m', peso: '250–2,300 kg', habitat: 'Océanos tropicales y templados', alimentacion: 'Carnívoro — medusas, zooplancton', edadMaxima: '10 años', comportamiento: 'Solitario. Sube a la superficie a termorregularse.', curiosidades: ['El pez óseo más pesado del mundo.','Pone 300 millones de huevos a la vez.','No tiene cola — nada con sus aletas dorsales.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Chordata', clase:'Actinopterygii', orden:'Tetraodontiformes', familia:'Molidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' },
          { nombre: 'Piraña roja', nombreCientifico: 'Pygocentrus nattereri', altura: '25–33 cm', peso: '1–2 kg', habitat: 'Ríos y lagunas de América del Sur', alimentacion: 'Carnívora — peces, carroña, frutos', edadMaxima: '10 años', comportamiento: 'Gregaria. Caza en grupos.', curiosidades: ['Sus dientes se reemplazan en tandas completas.','Su reputación es peor que su comportamiento real.','Los peces muertos les interesan más que los vivos.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Actinopterygii', orden:'Characiformes', familia:'Serrasalmidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' },
          { nombre: 'Pez espada', nombreCientifico: 'Xiphias gladius', altura: '2.5–4.5 m', peso: '100–650 kg', habitat: 'Océanos tropicales y templados, abierto', alimentacion: 'Carnívoro — calamares, peces pelágicos', edadMaxima: '9 años', comportamiento: 'Migratorio y solitario. Nada hasta 90 km/h.', curiosidades: ['Su "espada" es la mandíbula superior alargada.','Calienta su cerebro y ojos para cazar en aguas frías.','Caza de noche en aguas profundas y descansa de día.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Actinopterygii', orden:'Perciformes', familia:'Xiphiidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' },
          { nombre: 'Pez linterna', nombreCientifico: 'Myctophum punctatum', altura: '6–10 cm', peso: '5–10 g', habitat: 'Aguas profundas de todos los océanos', alimentacion: 'Carnívoro — copépodos, zooplancton', edadMaxima: '3 años', comportamiento: 'Hace migraciones verticales de cientos de metros cada día.', curiosidades: ['Bioluminiscente — tiene filas de fotóforos en el cuerpo.','Forma la mayor biomasa de peces del océano.','Sube de noche y baja de día para evitar depredadores.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Chordata', clase:'Actinopterygii', orden:'Myctophiformes', familia:'Myctophidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' }
        ]
      },
      {
        name: 'Cartilaginosos', icon: '🦈', color: 'bg-slate-400',
        imagen: 'https://i1-e.pinimg.com/1200x/d0/25/9f/d0259fc86cecb0ce097c00b0c8ae6775.jpg',
        descripcion: 'Tiburones, rayas y quimeras. Su esqueleto es de cartílago, no de hueso. No tienen vejiga natatoria, por lo que deben nadar constantemente para no hundirse.',
        animales: [
          { nombre: 'Gran tiburón blanco', nombreCientifico: 'Carcharodon carcharias', altura: '4.5–6 m', peso: '680–1,100 kg', habitat: 'Aguas costeras templadas de todos los océanos', alimentacion: 'Carnívoro — focas, leones marinos', edadMaxima: '70 años', comportamiento: 'Solitario y migratorio.', curiosidades: ['Detecta una gota de sangre en 100 litros.','Tiene 6 sentidos incluyendo electrorrecepción.','Debe nadar constantemente.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Chordata', clase:'Chondrichthyes', orden:'Lamniformes', familia:'Lamnidae', imagen:'https://images.unsplash.com/photo-1564894809611-1742fc40ed80?w=800&q=80' },
          { nombre: 'Tiburón ballena', nombreCientifico: 'Rhincodon typus', altura: '5.5–10 m', peso: '9,000–21,500 kg', habitat: 'Océanos tropicales y templados', alimentacion: 'Filtrador — plancton, peces pequeños', edadMaxima: '70–130 años', comportamiento: 'Solitario. Migraciones de miles de kilómetros.', curiosidades: ['El pez más grande del mundo.','Su boca puede tener 300 filas de dientes diminutos.','Se alimenta de lo más pequeño del océano.'], conservacion: 'En peligro (UICN)', reino:'Animalia', filo:'Chordata', clase:'Chondrichthyes', orden:'Orectolobiformes', familia:'Rhincodontidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' },
          { nombre: 'Manta raya gigante', nombreCientifico: 'Mobula birostris', altura: '4.5–7 m envergadura', peso: '1,350–2,000 kg', habitat: 'Océanos tropicales y subtropicales', alimentacion: 'Filtradora — plancton y pequeños crustáceos', edadMaxima: '40 años', comportamiento: 'Solitaria o en grupos pequeños. Salta fuera del agua.', curiosidades: ['El cerebro más grande de todos los peces.','Puede reconocerse en un espejo.','Las branquias son en forma de cuerno para filtrar el agua.'], conservacion: 'En peligro (UICN)', reino:'Animalia', filo:'Chordata', clase:'Chondrichthyes', orden:'Myliobatiformes', familia:'Mobulidae', imagen:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80' },
          { nombre: 'Tiburón martillo', nombreCientifico: 'Sphyrna lewini', altura: '3.5–4.3 m', peso: '150–230 kg', habitat: 'Costas tropicales y templadas', alimentacion: 'Carnívoro — peces, rayas, pulpos', edadMaxima: '30 años', comportamiento: 'Forma escuelas de cientos de individuos durante el día.', curiosidades: ['Su cabeza aplanada amplifica los electrosensores.','Puede detectar el campo eléctrico de un pez enterrado.','Da a luz crías vivas (vivíparo).'], conservacion: 'En peligro crítico (UICN)', reino:'Animalia', filo:'Chordata', clase:'Chondrichthyes', orden:'Carcharhiniformes', familia:'Sphyrnidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' }
        ]
      },
      {
        name: 'Sin Mandíbula', icon: '🐟', color: 'bg-indigo-300',
        imagen: 'https://i1-e.pinimg.com/736x/11/ac/20/11ac206d1f97578b55043cdf5aa06962.jpg',
        descripcion: 'Los agnatos o peces sin mandíbula son los vertebrados más primitivos. En lugar de mandíbula tienen una ventosa circular con dientes córneos para adherirse a sus presas.',
        animales: [
          { nombre: 'Lamprea de mar', nombreCientifico: 'Petromyzon marinus', altura: '60–120 cm', peso: '200–500 g', habitat: 'Ríos del Atlántico Norte y mar abierto', alimentacion: 'Parásita — sangre de peces', edadMaxima: '8 años', comportamiento: 'Migratoria. Nace en ríos, vive en el mar y regresa a desovar.', curiosidades: ['Sin cambios morfológicos en 360 millones de años.','No tiene mandíbula — usa ventosa con dientes.','La larva vive enterrada hasta 7 años.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Petromyzontida', orden:'Petromyzontiformes', familia:'Petromyzontidae', imagen:'https://images.unsplash.com/photo-1498503403619-e39e4ff390fe?w=800&q=80' },
          { nombre: 'Mixina del Atlántico', nombreCientifico: 'Myxine glutinosa', altura: '40–60 cm', peso: '100–200 g', habitat: 'Fondos marinos del Atlántico Norte', alimentacion: 'Necrófaga — cadáveres de peces y mamíferos marinos', edadMaxima: 'desconocida', comportamiento: 'Enterrada en el fango. Limpia cadáveres desde adentro.', curiosidades: ['Puede producir litros de moco en segundos para escapar.','No tiene mandíbula ni vértebras verdaderas.','Puede sobrevivir sin oxígeno horas con metabolismo anaeróbico.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Chordata', clase:'Myxini', orden:'Myxiniformes', familia:'Myxinidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      }
    ]
  },

  artropodos: {
    id: 'artropodos', name: 'Artrópodos', icon: '🕷️', headerIcon: '🦂',
    theme: 'bg-orange-700', pattern: 'bg-stone-900',
    descripcion: 'Los artrópodos son el filo animal más diverso del planeta. Se caracterizan por su exoesqueleto quitinoso, cuerpo segmentado y apéndices articulados.',
    imagen: 'https://i.pinimg.com/736x/39/8b/44/398b44161c8577651cfb7b0afc334100.jpg',
    subtypes: [
      {
        name: 'Insectos', icon: '🐝', color: 'bg-yellow-400',
        imagen: 'https://i1-e.pinimg.com/1200x/1c/a4/01/1ca401b59c22e76c63ec4ea4e7297a0d.jpg',
        descripcion: 'Los insectos son el grupo animal más numeroso de la Tierra. Tienen 3 pares de patas, 3 regiones corporales y la mayoría posee alas en estado adulto.',
        animales: [
          { nombre: 'Abeja melífera', nombreCientifico: 'Apis mellifera', altura: '1.5 cm', peso: '0.1 g', habitat: 'Todos los continentes excepto la Antártida', alimentacion: 'Polen y néctar', edadMaxima: '6 semanas (obrera), 5 años (reina)', comportamiento: 'Eusocial — colonias de hasta 60,000 individuos.', curiosidades: ['Poliniza el 70% de los cultivos humanos.','Comunica ubicación de alimento con danza.','Produce 1/12 de cucharadita de miel en su vida.'], conservacion: 'En declive global', reino:'Animalia', filo:'Arthropoda', clase:'Insecta', orden:'Hymenoptera', familia:'Apidae', imagen:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80' },
          { nombre: 'Mariposa monarca', nombreCientifico: 'Danaus plexippus', altura: '10 cm envergadura', peso: '0.27 g', habitat: 'América del Norte y Central', alimentacion: 'Nectarívora — flores de milkweed', edadMaxima: '8 meses (generación migradora)', comportamiento: 'Migra hasta 4,500 km al año. Navega con campo magnético.', curiosidades: ['Migra en nubes de millones de individuos.','El veneno de la milkweed la vuelve tóxica para depredadores.','Las mariposas de la migración nunca han hecho el viaje antes.'], conservacion: 'En peligro (UICN 2022)', reino:'Animalia', filo:'Arthropoda', clase:'Insecta', orden:'Lepidoptera', familia:'Nymphalidae', imagen:'https://images.unsplash.com/photo-1444464666168-49d633b86797?w=800&q=80' },
          { nombre: 'Mantis religiosa', nombreCientifico: 'Mantis religiosa', altura: '6–9 cm', peso: '1–3 g', habitat: 'Europa, Asia y África — praderas y jardines', alimentacion: 'Carnívora — insectos, lagartijas pequeñas', edadMaxima: '1 año', comportamiento: 'Emboscadora. La hembra devora al macho tras el apareamiento.', curiosidades: ['El único insecto capaz de girar la cabeza 180°.','Puede atrapar colibríes en vuelo.','Tiene visión 3D con un solo ojo compuesto.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Arthropoda', clase:'Insecta', orden:'Mantodea', familia:'Mantidae', imagen:'https://images.unsplash.com/photo-1550358864-518f202c02ba?w=800&q=80' },
          { nombre: 'Escarabajo Goliat', nombreCientifico: 'Goliathus goliatus', altura: '6–11 cm', peso: '70–100 g (larva hasta 100 g)', habitat: 'Bosques tropicales del África ecuatorial', alimentacion: 'Adulto: savia y frutas / Larva: madera en descomposición', edadMaxima: '1 año adulto', comportamiento: 'Solitario. Los machos combaten con sus cuernos.', curiosidades: ['El insecto más pesado del mundo.','Su larva puede pesar 100 g.','Produce un zumbido intenso al volar.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Arthropoda', clase:'Insecta', orden:'Coleoptera', familia:'Scarabaeidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' },
          { nombre: 'Luciérnaga común', nombreCientifico: 'Lampyris noctiluca', altura: '1–2.5 cm', peso: '0.05 g', habitat: 'Praderas y bordes de bosques de Europa y Asia', alimentacion: 'Larva carnívora — caracoles / Adulto no come', edadMaxima: '2 años (larva) + 3 semanas (adulto)', comportamiento: 'Las hembras emiten luz para atraer machos voladores.', curiosidades: ['Produce la bioluminiscencia más eficiente conocida (99% luz, 1% calor).','La hembra no tiene alas y brilla desde el suelo.','En declive severo por contaminación lumínica.'], conservacion: 'En declive (UICN)', reino:'Animalia', filo:'Arthropoda', clase:'Insecta', orden:'Coleoptera', familia:'Lampyridae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      },
      {
        name: 'Arácnidos', icon: '🕷️', color: 'bg-stone-600',
        imagen: 'https://i1-e.pinimg.com/1200x/89/1f/57/891f571a37e74559d7ce9d41ccdd57e4.jpg',
        descripcion: 'Arañas, escorpiones, ácaros y garrapatas. Tienen 4 pares de patas y 2 regiones corporales. Son principalmente depredadores y muchos producen veneno o seda.',
        animales: [
          { nombre: 'Tarántula roja de México', nombreCientifico: 'Brachypelma hamorii', altura: '13–15 cm envergadura', peso: '15–25 g', habitat: 'Zonas áridas del occidente de México', alimentacion: 'Carnívora — grillos, ratones pequeños', edadMaxima: '30 años (hembra)', comportamiento: 'Nocturna y solitaria. Lanza pelos urticantes.', curiosidades: ['Su veneno es menos potente que el de una abeja.','Las hembras son de las arañas más longevas.','Muda de exoesqueleto toda su vida.'], conservacion: 'Casi amenazado (UICN)', reino:'Animalia', filo:'Arthropoda', clase:'Arachnida', orden:'Araneae', familia:'Theraphosidae', imagen:'https://images.unsplash.com/photo-1563681353614-958ceac74baa?w=800&q=80' },
          { nombre: 'Araña viuda negra', nombreCientifico: 'Latrodectus mactans', altura: '3–13 mm', peso: '0.035–0.12 g', habitat: 'América, zonas templadas y cálidas', alimentacion: 'Carnívora — insectos atrapados en telaraña', edadMaxima: '3 años', comportamiento: 'Solitaria y nocturna. La hembra puede devorar al macho.', curiosidades: ['Su veneno es 15 veces más potente que el de una serpiente de cascabel.','La seda es más resistente que el acero a igual grosor.','La marca roja en el abdomen varía por individuo.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Arthropoda', clase:'Arachnida', orden:'Araneae', familia:'Theridiidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' },
          { nombre: 'Escorpión deathstalker', nombreCientifico: 'Leiurus quinquestriatus', altura: '5.8–8.5 cm', peso: '2–3 g', habitat: 'Desiertos de Oriente Medio y Norte de África', alimentacion: 'Carnívoro — insectos, arañas', edadMaxima: '5–8 años', comportamiento: 'Nocturno y solitario. Muy agresivo.', curiosidades: ['El veneno de escorpión más peligroso del mundo.','Su veneno puede valer $39 millones por litro — el líquido más caro del mundo.','Componentes de su veneno combaten células tumorales.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Arthropoda', clase:'Arachnida', orden:'Scorpiones', familia:'Buthidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      },
      {
        name: 'Crustáceos', icon: '🦀', color: 'bg-red-400',
        imagen: 'https://i.pinimg.com/736x/bc/82/7e/bc827e1742e5162dbf51bb479d60aa85.jpg',
        descripcion: 'Cangrejos, langostas, camarones y percebes. La mayoría son acuáticos. Tienen dos pares de antenas y el cuerpo cubierto por un caparazón calcificado.',
        animales: [
          { nombre: 'Cangrejo de herradura', nombreCientifico: 'Limulus polyphemus', altura: '30–60 cm', peso: '3–5 kg', habitat: 'Costa Atlántica de América del Norte', alimentacion: 'Omnívoro — gusanos, moluscos', edadMaxima: '20 años', comportamiento: 'Migra masivamente en primavera para reproducirse.', curiosidades: ['Su sangre azul es vital para testear vacunas.','450 millones de años sin cambios morfológicos.','No es un cangrejo verdadero — pariente de las arañas.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Arthropoda', clase:'Merostomata', orden:'Xiphosura', familia:'Limulidae', imagen:'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?w=800&q=80' },
          { nombre: 'Langosta común', nombreCientifico: 'Homarus gammarus', altura: '30–60 cm', peso: '0.5–5 kg', habitat: 'Fondos rocosos del Atlántico Norte y Mediterráneo', alimentacion: 'Omnívora — peces, moluscos, algas', edadMaxima: '60–70 años', comportamiento: 'Nocturna. Migra en fila india durante otoño.', curiosidades: ['No envejece biológicamente — sigue creciendo toda su vida.','Las más grandes registradas tenían más de 60 años.','Mudan su exoesqueleto periódicamente.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Arthropoda', clase:'Malacostraca', orden:'Decapoda', familia:'Nephropidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' },
          { nombre: 'Cangrejo yeti', nombreCientifico: 'Kiwa hirsuta', altura: '15 cm', peso: '50 g', habitat: 'Fuentes hidrotermales del Pacífico Sur', alimentacion: 'Cultivador — bacterias que cultiva en su pelaje', edadMaxima: 'desconocida', comportamiento: 'Agita los brazos para oxigenar las bacterias de su "pelaje".', curiosidades: ['Fue descubierto en 2005 — tan único que se creó una familia nueva.','Ciega por vivir en oscuridad total.','Las bacterias de su cuerpo son su única fuente de alimento.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Arthropoda', clase:'Malacostraca', orden:'Decapoda', familia:'Kiwaidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      },
      {
        name: 'Miriápodos', icon: '🐛', color: 'bg-orange-400',
        imagen: 'https://i1-e.pinimg.com/1200x/15/47/94/1547949948547cb94af8783a19841903.jpg',
        descripcion: 'Ciempiés y milpiés. Tienen un cuerpo alargado con muchos segmentos, cada uno con uno o dos pares de patas. Habitan en suelos húmedos y hojarasca.',
        animales: [
          { nombre: 'Milpiés gigante africano', nombreCientifico: 'Archispirostreptus gigas', altura: '30–38 cm', peso: '30–60 g', habitat: 'Bosques tropicales del este y sur de África', alimentacion: 'Detritívoro — hojas en descomposición', edadMaxima: '7 años', comportamiento: 'Nocturno. Se enrolla en bola al sentirse amenazado.', curiosidades: ['El miriápodo más grande del mundo.','Tiene entre 300 y 400 patas.','Segrega cianuro de hidrógeno como defensa.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Arthropoda', clase:'Diplopoda', orden:'Spirostreptida', familia:'Spirostreptidae', imagen:'https://images.unsplash.com/photo-1559767949-0faa5c7e9992?w=800&q=80' },
          { nombre: 'Ciempiés gigante amazónico', nombreCientifico: 'Scolopendra gigantea', altura: '25–30 cm', peso: '10–20 g', habitat: 'Selvas de América del Sur y el Caribe', alimentacion: 'Carnívoro — insectos, ratones, lagartijas, murciélagos', edadMaxima: '10 años', comportamiento: 'Nocturno y solitario. Caza activamente.', curiosidades: ['El ciempiés más grande del mundo.','Caza murciélagos colgado del techo de cuevas.','Sus venenos causan dolor intenso en humanos.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Arthropoda', clase:'Chilopoda', orden:'Scolopendromorpha', familia:'Scolopendridae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      }
    ]
  },

  moluscos: {
    id: 'moluscos', name: 'Moluscos', icon: '🐙', headerIcon: '🐙',
    theme: 'bg-fuchsia-800', pattern: 'bg-zinc-900',
    descripcion: 'Los moluscos son uno de los filos más diversos del reino animal. Tienen cuerpo blando, generalmente protegido por una concha calcárea, y un pie muscular para desplazarse.',
    imagen: 'https://i.pinimg.com/736x/a0/e5/7e/a0e57e0a2fa5fabd84b6cf0ef7e8681d.jpg',
    subtypes: [
      {
        name: 'Gasterópodos', icon: '🐌', color: 'bg-pink-400',
        imagen: 'https://i1-e.pinimg.com/736x/99/7e/75/997e7550c0e9ca5494f250101a56e7a6.jpg',
        descripcion: 'El grupo más diverso de moluscos. Incluye caracoles y babosas. Se desplazan sobre un pie muscular y la mayoría tiene una concha en espiral.',
        animales: [
          { nombre: 'Caracol gigante africano', nombreCientifico: 'Lissachatina fulica', altura: '20 cm concha', peso: '32 g', habitat: 'Bosques tropicales de África oriental', alimentacion: 'Herbívoro — más de 500 especies vegetales', edadMaxima: '9 años', comportamiento: 'Nocturno. Hermafrodita.', curiosidades: ['Una de las peores especies invasoras del mundo.','Puede transmitir meningitis.','Tiene 14,000 dientes microscópicos.'], conservacion: 'Plaga invasora', reino:'Animalia', filo:'Mollusca', clase:'Gastropoda', orden:'Stylommatophora', familia:'Achatinidae', imagen:'https://images.unsplash.com/photo-1497206365907-f5e630693df0?w=800&q=80' },
          { nombre: 'Nudibranquio dragón de mar', nombreCientifico: 'Glaucus atlanticus', altura: '3–8 cm', peso: '0.1 g', habitat: 'Superficie de océanos templados y tropicales', alimentacion: 'Carnívoro — carabelas portuguesas y otras medusas', edadMaxima: '1 año', comportamiento: 'Flota boca arriba en la superficie del océano.', curiosidades: ['Almacena las células urticantes de sus presas en sus propios tentáculos.','Es venenoso gracias a lo que come, no por naturaleza propia.','Su coloración azul lo camufla visto desde arriba y desde abajo.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Mollusca', clase:'Gastropoda', orden:'Nudibranchia', familia:'Glaucidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' },
          { nombre: 'Caracol cono', nombreCientifico: 'Conus geographus', altura: '10–16 cm', peso: '20–40 g', habitat: 'Arrecifes del Indo-Pacífico', alimentacion: 'Carnívoro — peces pequeños', edadMaxima: 'desconocida', comportamiento: 'Nocturno. Caza con un arpón venenoso extensible.', curiosidades: ['Responsable de más muertes humanas que cualquier otro molusco.','Su conotoxina bloquea canales de sodio — sin antídoto.','Los compuestos de su veneno se usan en analgésicos potentes.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Mollusca', clase:'Gastropoda', orden:'Neogastropoda', familia:'Conidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      },
      {
        name: 'Bivalvos', icon: '🦪', color: 'bg-slate-300',
        imagen: 'https://i.pinimg.com/736x/d5/b3/52/d5b352da07b63ccce8daeaacf6c6c5d2.jpg',
        descripcion: 'Mejillones, almejas, ostras y vieiras. Tienen dos valvas que protegen su cuerpo blando. Son filtradores que purifican el agua y son fundamentales en los ecosistemas acuáticos.',
        animales: [
          { nombre: 'Almeja gigante', nombreCientifico: 'Tridacna gigas', altura: '120 cm', peso: 'hasta 250 kg', habitat: 'Arrecifes de coral del Indo-Pacífico', alimentacion: 'Filtradora y fotosintética por algas simbióticas', edadMaxima: 'más de 100 años', comportamiento: 'Completamente sedentaria de adulta.', curiosidades: ['El molusco bivalvo más grande del mundo.','Las algas producen hasta 70% de sus nutrientes.','Sus perlas son las más grandes del mundo.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Mollusca', clase:'Bivalvia', orden:'Cardiida', familia:'Cardiidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' },
          { nombre: 'Ostra perla', nombreCientifico: 'Pinctada margaritifera', altura: '15–30 cm', peso: '200–500 g', habitat: 'Lagunas tropicales del Indo-Pacífico', alimentacion: 'Filtradora — fitoplancton', edadMaxima: '30 años', comportamiento: 'Sedentaria. Se adhiere a sustratos.', curiosidades: ['Produce las perlas negras de Tahití más valoradas del mundo.','Una perla tarda entre 2 y 5 años en formarse.','Filtra hasta 100 litros de agua al día.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Mollusca', clase:'Bivalvia', orden:'Pteriida', familia:'Pteriidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' },
          { nombre: 'Mejillón cebra', nombreCientifico: 'Dreissena polymorpha', altura: '4–5 cm', peso: '1–3 g', habitat: 'Ríos y lagos de Europa y América del Norte', alimentacion: 'Filtrador — fitoplancton', edadMaxima: '5 años', comportamiento: 'Forma colonias densas sobre cualquier superficie dura.', curiosidades: ['Una de las peores especies invasoras del agua dulce.','Un solo mejillón filtra hasta 1 litro de agua al día.','Obstruye tuberías e infraestructuras hidráulicas.'], conservacion: 'Especie invasora', reino:'Animalia', filo:'Mollusca', clase:'Bivalvia', orden:'Veneroida', familia:'Dreissenidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      },
      {
        name: 'Cefalópodos', icon: '🦑', color: 'bg-purple-500',
        imagen: 'https://i1-e.pinimg.com/1200x/c6/94/6b/c6946b2bc93524354031287413cd980c.jpg',
        descripcion: 'Pulpos, calamares y nautilus. Los invertebrados más inteligentes del reino animal. Tienen tentáculos con ventosas, pueden cambiar de color y tienen sistemas nerviosos complejos.',
        animales: [
          { nombre: 'Pulpo común', nombreCientifico: 'Octopus vulgaris', altura: '60–90 cm', peso: '3–10 kg', habitat: 'Todos los océanos, fondos rocosos', alimentacion: 'Carnívoro — cangrejos, mejillones', edadMaxima: '1–2 años', comportamiento: 'Solitario. Usa herramientas y resuelve laberintos.', curiosidades: ['3 corazones, sangre azul y 9 cerebros.','Cambia color y textura en menos de un segundo.','Las hembras mueren al eclosionar los huevos.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Mollusca', clase:'Cephalopoda', orden:'Octopoda', familia:'Octopodidae', imagen:'https://images.unsplash.com/photo-1498503403619-e39e4ff390fe?w=800&q=80' },
          { nombre: 'Calamar gigante', nombreCientifico: 'Architeuthis dux', altura: '10–13 m (con tentáculos)', peso: '275 kg', habitat: 'Aguas profundas de todos los océanos', alimentacion: 'Carnívoro — peces y otros calamares', edadMaxima: '5 años', comportamiento: 'Solitario en aguas de 200–1,000 m. Caza con ventosas dentadas.', curiosidades: ['El invertebrado más grande del mundo.','Sus ojos miden 30 cm — los más grandes del reino animal.','Fue fotografiado vivo por primera vez en 2004.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Mollusca', clase:'Cephalopoda', orden:'Oegopsida', familia:'Architeuthidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' },
          { nombre: 'Sepia común', nombreCientifico: 'Sepia officinalis', altura: '15–45 cm', peso: '0.5–4 kg', habitat: 'Costas arenosas del Atlántico Este y Mediterráneo', alimentacion: 'Carnívora — camarones, peces, cangrejos', edadMaxima: '2 años', comportamiento: 'Solitaria. Los machos hacen exhibiciones de color para las hembras.', curiosidades: ['Puede crear patrones hipnóticos en su piel para hipnotizar presas.','Tiene la mayor densidad de fotoreceptores de cualquier ojo.','Su "jiba" es una concha interna que controla flotabilidad.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Mollusca', clase:'Cephalopoda', orden:'Sepiida', familia:'Sepiidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' }
        ]
      }
    ]
  },

  equinodermos: {
    id: 'equinodermos', name: 'Equinodermos', icon: '⭐', headerIcon: '🌟',
    theme: 'bg-rose-600', pattern: 'bg-slate-900',
    descripcion: 'Los equinodermos son exclusivamente marinos. Se caracterizan por su simetría radial pentámera (5 partes), su endoesqueleto calcáreo y su sistema vascular acuífero único.',
    imagen: 'https://i1-e.pinimg.com/1200x/40/6c/3a/406c3a0f3c582e12cbe2b0b9b2c886b2.jpg',
    subtypes: [
      {
        name: 'Asteroideos', icon: '⭐', color: 'bg-orange-300',
        imagen: 'https://i1-e.pinimg.com/1200x/64/05/1d/64051deb97e35fd3ac9638ba03106434.jpg',
        descripcion: 'Las estrellas de mar. Tienen generalmente 5 brazos y se mueven mediante pies ambulacrales con ventosas. Son depredadores activos capaces de evertir su estómago.',
        animales: [
          { nombre: 'Estrella de mar común', nombreCientifico: 'Asterias rubens', altura: '10–30 cm diámetro', peso: '5–100 g', habitat: 'Fondos rocosos del Atlántico Norte', alimentacion: 'Carnívora — mejillones, ostras', edadMaxima: '34 años', comportamiento: 'Solitaria. Evierte el estómago para digerir externamente.', curiosidades: ['Puede regenerar brazos completos.','Usa agua de mar como sistema circulatorio.','Cientos de pies ambulacrales con ventosas.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Echinodermata', clase:'Asteroidea', orden:'Forcipulatida', familia:'Asteriidae', imagen:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80' },
          { nombre: 'Estrella corona de espinas', nombreCientifico: 'Acanthaster planci', altura: '25–35 cm diámetro', peso: '3–8 kg', habitat: 'Arrecifes de coral del Indo-Pacífico', alimentacion: 'Carnívora — coral vivo (pólipos)', edadMaxima: '8 años', comportamiento: 'Se alimenta de noche sobre el coral.', curiosidades: ['Tiene hasta 21 brazos cubiertos de espinas venenosas.','Considerada la mayor amenaza biológica para la Gran Barrera de Coral.','Una sola puede destruir 6 m² de coral por semana.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Echinodermata', clase:'Asteroidea', orden:'Valvatida', familia:'Acanthasteridae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      },
      {
        name: 'Equinoideos', icon: '🐡', color: 'bg-rose-400',
        imagen: 'https://i1-e.pinimg.com/1200x/44/d1/f5/44d1f5aae2ec264155b18a6de6480174.jpg',
        descripcion: 'Los erizos de mar y los dólares de arena. Tienen un caparazón esférico cubierto de espinas móviles. Son herbívoros que raspan algas con su aparato masticador de 5 piezas.',
        animales: [
          { nombre: 'Erizo de mar rojo', nombreCientifico: 'Mesocentrotus franciscanus', altura: '19 cm diámetro', peso: '500 g', habitat: 'Costas rocosas del Pacífico Norte', alimentacion: 'Herbívoro — kelp, algas', edadMaxima: 'más de 200 años', comportamiento: 'Gregario. Se desplaza con pies ambulacrales.', curiosidades: ['Uno de los animales más longevos del planeta.','Su aparato masticador se llama "linterna de Aristóteles".','No muestra signos de envejecimiento biológico.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Echinodermata', clase:'Echinoidea', orden:'Camerodonata', familia:'Strongylocentrotidae', imagen:'https://images.unsplash.com/photo-1534043464124-3be32fe000c9?w=800&q=80' },
          { nombre: 'Dólar de arena', nombreCientifico: 'Echinarachnius parma', altura: '6–10 cm diámetro', peso: '20–50 g', habitat: 'Fondos arenosos del Atlántico y Pacífico Norte', alimentacion: 'Detritívoro — materia orgánica del sedimento', edadMaxima: '10 años', comportamiento: 'Vive semienterrado en arenas.', curiosidades: ['Su nombre viene de su parecido a una moneda.','Tiene miles de espinas microscópicas que mueve para desplazarse.','El color morado se debe a un pigmento llamado espinocromo.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Echinodermata', clase:'Echinoidea', orden:'Clypeasteroidea', familia:'Echinarachniidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      },
      {
        name: 'Holoturoideos', icon: '🥒', color: 'bg-green-500',
        imagen: 'https://i1-e.pinimg.com/736x/79/d7/6a/79d76afe7707f47cd723ebf21762d41c.jpg',
        descripcion: 'Los pepinos de mar. Tienen cuerpo alargado y blando, sin espinas visibles. Son detritívoros que filtran el sedimento marino y juegan un papel clave en el reciclaje de nutrientes.',
        animales: [
          { nombre: 'Pepino de mar gigante', nombreCientifico: 'Holothuria fuscogilva', altura: '30–50 cm', peso: '500 g–1.5 kg', habitat: 'Fondos arenosos del Indo-Pacífico', alimentacion: 'Detritívoro — sedimento orgánico', edadMaxima: '5–10 años', comportamiento: 'Lento. Expulsa sus vísceras al sentirse amenazado.', curiosidades: ['Puede regenerar órganos internos completos.','Es el "reciclador" del ecosistema marino.','Su cuerpo puede volverse rígido o líquido.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Echinodermata', clase:'Holothuroidea', orden:'Aspidochirotida', familia:'Holothuriidae', imagen:'https://images.unsplash.com/photo-1497206365907-f5e630693df0?w=800&q=80' },
          { nombre: 'Pepino real del Pacífico', nombreCientifico: 'Parastichopus californicus', altura: '50 cm', peso: '1–2 kg', habitat: 'Fondos de kelp del Pacífico Norte', alimentacion: 'Detritívoro — detritos orgánicos', edadMaxima: '12 años', comportamiento: 'Lento y solitario. Pasa el verano en latencia.', curiosidades: ['Se "funde" y escurre entre grietas estrechísimas.','Su dermis contiene espículas calcáreas microscópicas.','Entra en estivación (latencia estival) en aguas cálidas.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Echinodermata', clase:'Holothuroidea', orden:'Aspidochirotida', familia:'Stichopodidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      }
    ]
  },

  anelidos: {
    id: 'anelidos', name: 'Anélidos', icon: '🪱', headerIcon: '🪱',
    theme: 'bg-stone-600', pattern: 'bg-zinc-900',
    descripcion: 'Los anélidos son gusanos segmentados. Su cuerpo está dividido en anillos o metámeros repetidos. Habitan en suelos, agua dulce y mar. Son fundamentales para la fertilidad del suelo.',
    imagen: 'https://i.pinimg.com/736x/a1/88/0b/a1880bee2a0e348f6a43ee553d013685.jpg',
    subtypes: [
      {
        name: 'Oligoquetos', icon: '🪱', color: 'bg-orange-200',
        imagen: 'https://i.pinimg.com/736x/4b/2b/df/4b2bdf6a549762a41b376e0838efe5bb.jpg',
        descripcion: 'Las lombrices de tierra. Viven en suelos húmedos y son esenciales para la fertilidad agrícola. Al desplazarse airean y fertilizan el suelo con sus excrementos.',
        animales: [
          { nombre: 'Lombriz gigante de Gippsland', nombreCientifico: 'Megascolides australis', altura: 'hasta 3 m', peso: '200 g', habitat: 'Suelos arcillosos de Victoria, Australia', alimentacion: 'Detritívora — materia orgánica del suelo', edadMaxima: '5 años', comportamiento: 'Subterránea. Produce sonido de gorgoteo audible desde la superficie.', curiosidades: ['La lombriz más grande del mundo.','Tarda hasta 5 años en alcanzar su tamaño.','Su mucus mantiene húmedos sus túneles.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Annelida', clase:'Clitellata', orden:'Opisthopora', familia:'Megascolecidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' },
          { nombre: 'Lombriz de tierra común', nombreCientifico: 'Lumbricus terrestris', altura: '9–30 cm', peso: '1–3 g', habitat: 'Suelos húmedos y fértiles del hemisferio norte', alimentacion: 'Detritívora — hojas muertas y materia orgánica', edadMaxima: '6 años', comportamiento: 'Cava galerías que ventilan el suelo.', curiosidades: ['Mueve tierra equivalente a 20 kg por m² al año.','Hermafrodita — cada individuo puede reproducirse.','Charles Darwin estudió las lombrices durante 40 años.'], conservacion: 'Preocupación menor (UICN)', reino:'Animalia', filo:'Annelida', clase:'Clitellata', orden:'Opisthopora', familia:'Lumbricidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      },
      {
        name: 'Poliquetos', icon: '🐛', color: 'bg-emerald-300',
        imagen: 'https://i1-e.pinimg.com/736x/a0/fe/cc/a0fecc92d1ea74f0436ebcd80bfae70c.jpg',
        descripcion: 'Gusanos marinos con múltiples cerdas o quetas en cada segmento. Son el grupo más diverso de anélidos. Algunos son sedentarios y construyen tubos; otros son depredadores activos.',
        animales: [
          { nombre: 'Gusano de fuego', nombreCientifico: 'Hermodice carunculata', altura: '30 cm', peso: '10–15 g', habitat: 'Arrecifes del Atlántico tropical y Mediterráneo', alimentacion: 'Carnívoro — corales, esponjas, anémonas', edadMaxima: 'desconocida', comportamiento: 'Lento pero agresivo. Sus setas se clavan al tocarlo.', curiosidades: ['Sus setas huecas causan ardor intenso al romperse.','Uno de los pocos depredadores de corales de fuego.','Puede regenerar segmentos dañados.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Annelida', clase:'Polychaeta', orden:'Phyllodocida', familia:'Amphinomidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' },
          { nombre: 'Gusano de Navidad', nombreCientifico: 'Spirobranchus giganteus', altura: '3–4 cm', peso: '1 g', habitat: 'Arrecifes de coral de todos los trópicos', alimentacion: 'Filtrador — fitoplancton', edadMaxima: '40 años', comportamiento: 'Vive en un tubo calcáreo dentro del coral. Se retrae en menos de 0.02 s.', curiosidades: ['Sus dos espirales de plumas sirven para respirar y alimentarse.','Viene en decenas de colores vibrantes.','Nunca abandona su tubo una vez establecido.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Annelida', clase:'Polychaeta', orden:'Canalipalpata', familia:'Serpulidae', imagen:'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80' }
        ]
      },
      {
        name: 'Hirudíneos', icon: '🩸', color: 'bg-red-800',
        imagen: 'https://i1-e.pinimg.com/1200x/72/98/f6/7298f624802b4ea319b0c96c9eb63ed3.jpg',
        descripcion: 'Las sanguijuelas. Sin cerdas. Tienen una ventosa anterior y otra posterior para anclarse. La mayoría son ectoparásitos que se alimentan de sangre.',
        animales: [
          { nombre: 'Sanguijuela medicinal', nombreCientifico: 'Hirudo medicinalis', altura: '10–20 cm', peso: '1.5 g', habitat: 'Estanques y ríos limpios de Europa y Asia', alimentacion: 'Hematófaga — sangre de vertebrados', edadMaxima: '20 años', comportamiento: 'Solitaria. Puede pasar meses sin alimentarse.', curiosidades: ['Usada en medicina moderna post-cirugía.','Su saliva contiene el anticoagulante natural más potente.','Tiene 10 estómagos para almacenar sangre.'], conservacion: 'Vulnerable (UICN)', reino:'Animalia', filo:'Annelida', clase:'Clitellata', orden:'Hirudinida', familia:'Hirudinidae', imagen:'https://images.unsplash.com/photo-1564894809611-1742fc40ed80?w=800&q=80' },
          { nombre: 'Sanguijuela de caballo', nombreCientifico: 'Haemopis sanguisuga', altura: '8–15 cm', peso: '2–5 g', habitat: 'Estanques y ríos de Europa', alimentacion: 'Carnívora — lombrices, caracoles, renacuajos', edadMaxima: '10 años', comportamiento: 'Depredadora activa, no solo parásita. Se mueve fuera del agua.', curiosidades: ['A diferencia de la medicinal, traga a su presa entera.','Puede vivir varios meses sin comer.','Es hermafrodita y fecundación cruzada.'], conservacion: 'No evaluado (UICN)', reino:'Animalia', filo:'Annelida', clase:'Clitellata', orden:'Hirudinida', familia:'Haemopidae', imagen:'https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=800&q=80' }
        ]
      }
    ]
  }
};

module.exports = {
  getAll: () => categoriesData,
  getById: (id) => categoriesData[id],
  getSubtype: (categoriaId, subtypeName) => {
    const cat = categoriesData[categoriaId];
    if (!cat) return null;
    return cat.subtypes.find(s => s.name.toLowerCase() === subtypeName.toLowerCase());
  }
};